target_project_name: BookStoreTexture
copyright: Elon Park
template_path: ./Scaffold/templates
source_dir: ./BookStoreTexture/Sources/Scenes
test_dir: ./BookStoreTexture/BookStoreTextureTests/Scenes
indentation: 2