use_frameworks!

platform :ios, '13.0'

target 'BookStoreTextureUI_Example' do
  pod 'Texture', :git => 'https://github.com/TextureGroup/Texture.git'
  pod 'BookStoreTextureUI', :path => '../'

  target 'BookStoreTextureUI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
