# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'BookStoreTexture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookStoreTexture

  target 'BookStoreTextureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookStoreTextureUITests' do
    # Pods for testing
  end

end
