///
/// @Generated by Mockolo
///



import Foundation
import Moya
import Reachability
@testable import BookStoreTexture


class ReachabilityManageableMock: ReachabilityManageable {
    init() { }


    private(set) var configureReachabilityCallCount = 0
    var configureReachabilityHandler: (() -> ())?
    func configureReachability()  {
        configureReachabilityCallCount += 1
        if let configureReachabilityHandler = configureReachabilityHandler {
            configureReachabilityHandler()
        }
        
    }
}

